<a href="https://colab.research.google.com/github/Reema1234ag/Machine-Learning-Lab/blob/main/fundamentals_of_python(ML_lab).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Check Python Version
from platform import python_version    #The platform module in Python is used to access the underlying platform's data, such as, hardware,
#operating system, and interpreter version information.
print(python_version())


3.6.9


In [ ]:
# How to check Package version
#!pip show numpy
import numpy
print(numpy.__version__)


1.19.5


In [ ]:
# Multi-Line Statements
days = ['Monday', 'Tuesday', 'Wednesday',
'Thursday', 'Friday']
item_one, item_two, item_three = 'one', 'two', 'three'
total = item_one + \
item_two + \
item_three
print(total)
print(days)


onetwothree
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']


In [ ]:
#Quotation in Python
word = 'word'
sentence = "This is a sentence."
paragraph = """This is a paragraph. It is
made up of multiple lines and sentences."""
print(paragraph)


This is a paragraph. It is
made up of multiple lines and sentences.


In [ ]:
import sys; x = 'Dr. Neeraj Gupta'; sys.stdout.write(x + '\n')
for i in range(10): print("A", end= " " ); print("B", end = " ")
for i in range(10): print("\n i equals Value") if i==7 else None
for i in range(80, 90): print(i, end=" ") if (i!=89) else print(i)


Dr. Neeraj Gupta
A B A B A B A B A B A B A B A B A B A B 
 i equals Value
80 81 82 83 84 85 86 87 88 89


In [ ]:
counter = 5# An integer
miles = 1000.0 # A floating point
name = "Dr Neeraj Gupta" # A string
print(type( counter))

#sys.getsizeof() returns the memory size of the object in bytes

print(sys.getsizeof(counter)) # returns 28 bytes
print(sys.getsizeof("")) #returns 51 as its tuple
print(sys.getsizeof([])) #returns 64 as its list


<class 'int'>
28
53
64


In [ ]:
a = b = c = 1
a, b, c = 1, 2, "RAM"
print(a)
print(b)
print(c)


1
2
RAM


In [ ]:
print(0o10) # Octal 8
print(0x10) # Hexa
print(0b10) # Binary
print(type(10))
print(4.2e-4) # 0.00042
print(.4e7)  #4000000.0
print(type(2+3j)) #complex


8
16
2
<class 'int'>
0.00042
4000000.0
<class 'complex'>


In [ ]:
str= 'Hello World!'
print(str) # Prints complete string
print(str[0]) # Prints first character of the string
print(str[2:5]) # Prints characters starting from 3rd to 5th
print(str[2:]) # Prints string starting from 3rd character
print(str* 2) # Prints string two times
print(str+ "TEST") # Prints concatenated string
print(str[:-2]) # Hello Worl
print(str[-2]) #d
print(str[-2:]) #d!
print(str[::-1]) # Reverse !dlroWolleH
print(str[::-2]) # Alternative reverse !lo le
len(str) # 12 including space
str.count(' ') # Space Count


Hello World!
H
llo
llo World!
Hello World!Hello World!
Hello World!TEST
Hello Worl
d
d!
!dlroW olleH
!lo le


1

In [ ]:
tuple = ('xyz', 123, 1.23, 'RAM', 17.5 )
tinytuple= (123, 'RAM')
print(tuple) # Prints complete list
print(tuple[0]) # Prints first element of the list
print(tuple[1:3]) # Prints elements starting from 2nd till 3rd
print(tuple[2:]) # Prints elements starting from 3rd element
print(tinytuple* 2) # Prints list two times
print (tuple + tinytuple) # Prints concatenated lists
#tuple.append('Dr Neeraj Gupta') # Not Applicable


('xyz', 123, 1.23, 'RAM', 17.5)
xyz
(123, 1.23)
(1.23, 'RAM', 17.5)
(123, 'RAM', 123, 'RAM')
('xyz', 123, 1.23, 'RAM', 17.5, 123, 'RAM')


In [ ]:
dict= {}
dict['one'] = "This is one"
dict[2] = "This is two"
print(dict)
tinydict= {'name': 'RAM','code':'8989', 'dept': 'IT'}
print(dict['one']) # Prints value for 'one' key
print(dict[2]) # Prints value for 2 key
print(tinydict) # Prints complete dictionary
print(tinydict.keys()) # Prints all the keys
print(tinydict.values()) # Prints all the values


{'one': 'This is one', 2: 'This is two'}
This is one
This is two
{'name': 'RAM', 'code': '8989', 'dept': 'IT'}
dict_keys(['name', 'code', 'dept'])
dict_values(['RAM', '8989', 'IT'])


In [ ]:
T1=(10,50,20,9,40,25,60,30,1,56)
print(T1[0])
L1=list(T1)
L1[5]=100
T1=tuple(L1)
T1


10


TypeError: ignored

In [ ]:
#Single-dimensional Numpy Array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#Multi-dimensional Array
a = np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#comparing memory occupied by both
import numpy as np
import sys
#memory occupied by list
s = range(1000)
print('memory occupied by List',sys.getsizeof(10)*len(s))
#memory occupied by numpy
d = np.arange(1000)
print('memory occupied by Numpy Array',d.size*d.itemsize)

memory occupied by List 28000
memory occupied by Numpy Array 8000


In [ ]:
import time
print(time.time())

1611725326.3605347


In [ ]:
import time
#comparing speed of list and numpy array
size = 10000000
#checking list taken time
l1 = range(size)
l2 = range(size)
start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print('Time taken by List:', time.time()-start)
#checking numpy array taken time
a1 = np.arange(size)
a2 = np.arange(size)
start2 = time.time()
result_numpy = a1+a2
print('Time taken by numpy:', time.time()-start2)

Time taken by List: 1.8507330417633057
Time taken by numpy: 0.03788018226623535


In [ ]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(7, 0, -3)

array([7, 4, 1])

In [ ]:
# if you provide equal values for start and stop, 
# then you will get an empty array
print(np.arange(0))
np.arange(2,2)
np.arange(8,2,1)
np.arange(2,8,-1)

[]


array([], dtype=int64)

In [ ]:
# ndim
# Find the dimension of the array, whether it is a two-dimensional array or a single dimensional array
import numpy as np
a = np.array([(1,2,3),(4,5,6)])
print(a)
a1 = np.array([((1,2,3),(4,5,6)),((1,2,3),(4,5,6))])
print(a1)
print(a.ndim)
print(a1.ndim)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
2
3


In [ ]:
# itemsize
# •calculate the byte size of each element
import numpy as np
a = np.array([(1,2,3)])
print(a.itemsize)

8


In [ ]:
# dtype
# •find the data type of the elements that are stored in anarray. So, if you want to know the data type of a particular element, you can use‘dtype’ function which will print the datatypealong with the size.
import numpy as np
a = np.array([(1,2,3)])
print(a.dtype)

int64


In [ ]:
# ‘size’ and ‘shape’
# •find the size and shape of the array using ‘size’ and ‘shape’ function respectively.
import numpy as np
a = np.array([(1,2,3,4,5,6)])
a1 = np.array([(1,2,3,3),(4,5,6,4)])
print(a1)
print(a1.size)
print(a1.shape)

[[1 2 3 3]
 [4 5 6 4]]
8
(2, 4)


In [ ]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
b = a.reshape(6,1)
print(b)

[[ 8  9 10]
 [11 12 13]]
[[ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [ ]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
b = a.reshape(5,1)
print(b)

[[ 8  9 10]
 [11 12 13]]


ValueError: ignored

In [ ]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
b = a.reshape(3,2)       //multipication should be 6
print(b)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [ ]:
import numpy as np
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print(a[1,3])

[[1 2 3 4]
 [3 4 5 6]]
6


In [ ]:
import numpy as np
a = np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1])

[ 9 11]


In [ ]:
# 2nd element from the zeroth and first index of the array
import numpy as np
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:, 2])

[3 5]


In [ ]:
#It has printed 10 values between 1 to 3
import numpy as np
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [ ]:
import numpy as np
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6
